n = input('Digite algo: ')
alf = n.isalpha()
alfn = n.isalnum()
num = n.isnumeric()
tipo = (type(n))
espaço = n.isspace()
maiusc = n.isupper()
minusc = n.islower()
capital = n.istitle()
print('Qual é o tipo primitivo de {}?'.format(n), tipo)
print('O valor {} só tem espaços?'.format(n), espaço)
print('{} é numérico?'.format(n), num)
print('{} pertence ao alfabeto?'.format(n), alf)
print('{} é alfanumérico?'.format(n), alfn)
print('O valor {} é todo em letras maiúsculas?'.format(n), maiusc)
print('O valor {} é todo em letras minúsculas?'.format(n), minusc)
print('O valor {} está capitalizado?'.format(n), capital)


